// <auto-generated />
using Area.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Area.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20240126075636_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Area.Data.Atasozu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Atasozleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icerik = "atasozu1"
                        },
                        new
                        {
                            Id = 2,
                            Icerik = "atasozu2"
                        },
                        new
                        {
                            Id = 3,
                            Icerik = "atasozu3"
                        },
                        new
                        {
                            Id = 4,
                            Icerik = "atasozu4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
